---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu16.04
    box: ubuntu/xenial64
  - name: centos7
    box: centos/7
#  - name: centos6
#    box: centos/6
provisioner:
  name: ansible
  options:
    become: True
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: True
  lint:
    name: flake8
